In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import *
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras.applications import densenet #DenseNet121
import os
import cv2
from numpy import asarray
from PIL import Image
from functools import partial
from keras.applications import imagenet_utils
print('s')

s


In [2]:
load_model = keras.models.load_model('densenet121_detection_model.h5')

In [3]:
face_clsfr=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [4]:
labels_dict={0:'without_mask',1:'with_mask'}
color_dict={0:(0,0,255),1:(0,255,0)}

size = 4
cv2.namedWindow("COVID Mask Detection Video Feed")
webcam = cv2.VideoCapture(0) 

classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

while True:
    rval, im = webcam.read()
    im=cv2.flip(im,1,1)
    
    mini = cv2.resize(im, (im.shape[1] // size, im.shape[0] // size))
 
    faces = classifier.detectMultiScale(mini)

    for f in faces:
        (x, y, w, h) = [v * size for v in f] 
        face_img = im[y:y+h, x:x+w]
        resized=cv2.resize(face_img,(224,224))
        normalized=resized/255.0
        reshaped=np.reshape(normalized,(1,224,224,3))
        reshaped = np.vstack([reshaped])
        result=load_model.predict(reshaped)
        print(result)
        if result[0][0] > result[0][1]:
            percent = round(result[0][0]*100,2)
        else:
            percent = round(result[0][1]*100,2)
        
        label=np.argmax(result,axis=1)[0]
      
        cv2.rectangle(im,(x,y),(x+w,y+h),color_dict[label],2)
        cv2.rectangle(im,(x,y-40),(x+w,y),color_dict[label],-1)
        cv2.putText(im, labels_dict[label] + " " + str(percent) + "%", (x, y-10),cv2.FONT_HERSHEY_SIMPLEX,0.8,(255,255,255),2)
        
    if im is not None:   
        cv2.imshow('COVID Mask Detection Video Feed', im)
    if cv2.waitKey(1) & 0xFF == ord('q'): 
        break
        
# Stop video
webcam.release()

# Close all windows
cv2.destroyAllWindows()

[[0.00109317 0.99890685]]
[[0.11125495 0.88874507]]
[[0.01258591 0.98741406]]
[[0.0129263  0.98707366]]
[[0.00140398 0.998596  ]]
[[0.02032909 0.97967094]]
[[0.00109837 0.9989016 ]]
[[0.00606151 0.99393845]]
[[0.00296564 0.9970343 ]]
[[0.12380059 0.8761994 ]]
[[0.12358158 0.8764184 ]]
[[0.02302368 0.97697634]]
[[0.0164679 0.9835321]]
[[0.02588286 0.97411716]]
[[0.02081602 0.9791839 ]]
[[0.03814721 0.96185285]]
[[0.0185329  0.98146707]]
[[0.01363443 0.98636556]]
[[0.05099888 0.94900113]]
[[0.00648867 0.9935114 ]]
[[0.37214416 0.6278559 ]]
[[2.2264456e-05 9.9997771e-01]]
[[0.00727463 0.9927254 ]]
[[2.2276424e-06 9.9999774e-01]]
[[0.00154205 0.9984579 ]]
[[1.0963908e-05 9.9998903e-01]]
[[6.4668689e-05 9.9993527e-01]]
[[6.355985e-06 9.999937e-01]]
[[1.2000481e-04 9.9987996e-01]]
[[1.18908065e-05 9.99988079e-01]]
[[0.00825833 0.99174166]]
[[0.4223387 0.5776613]]
[[0.06387707 0.93612295]]
[[0.27614158 0.72385836]]
[[0.03851181 0.96148825]]
[[0.00191189 0.99808806]]
[[1.4551707e-04 9.9985445e